name: shonenx
description: "Minimal yet feature-rich Anime/Manga Client"
publish_to: "none"
version: 2.0.5+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.2.1
  flutter_riverpod: ^3.3.1
  flex_color_scheme: ^8.3.1
  logger: ^2.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0
  flutter_secure_storage: ^10.0.0
  flutter_web_auth_2:
    git:
      url: https://github.com/roshancodespace/flutter_web_auth.git
      path: flutter_web_auth_2
  anymex_extension_runtime_bridge:
    path: packages/anymex_extension_bridge
  commentum_client:
    path: packages/commentum_client
  media_kit:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit
  media_kit_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: media_kit_video
  media_kit_libs_video:
    git:
      url: https://github.com/Schnitzel5/media-kit.git
      path: libs/universal/media_kit_libs_video
  get: ^4.7.3
  google_fonts: ^8.0.2
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1
  rxdart: ^0.28.0
  volume_controller: ^3.4.4
  screen_brightness: ^2.1.7
  http: ^1.6.0
  flutter_inappwebview:
    git:
      url: https://github.com/roshancodespace/flutter_inappwebview.git
      path: flutter_inappwebview
  flutter_local_notifications: ^20.1.0
  timezone: ^0.10.1
  flutter_timezone: ^5.1.0
  screenshot: ^3.0.0
  window_manager: ^0.5.1
  url_launcher: ^6.3.0
  better_player:
    git:
      url: https://github.com/frostnova721/betterplayer.git
  html: ^0.15.6
  flutter_svg: ^2.2.4
  dynamic_system_colors: ^1.9.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  encrypt: ^5.0.3
  device_apps: ^2.2.0
  android_intent_plus: ^6.0.0
  open_file: ^3.5.11
  device_info_plus: ^12.4.0
  package_info_plus: ^8.3.0
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.2
  collection: ^1.19.1
  app_links: ^6.4.1
  flutter_launcher_icons: ^0.14.4
  video_player: ^2.10.1
  fvp: ^0.37.3
  wakelock_plus: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_community_generator: ^3.3.0
  package_rename: ^1.10.1
  inno_bundle: ^0.11.2

flutter:
  uses-material-design: true

inno_bundle:
  id: 17cd6e7b-cedc-43b7-86b1-4de6ab23dd4d
  name: ShonenX
  installer_icon: assets/images/installer.ico
  description: Anilist & MAL Client with extension support, for Anime lovers.
  publisher: roshancodespace
  url: https://github.com/roshancodespace/shonenx
  support_url: https://github.com/roshancodespace/shonenx/issues
  updates_url: https://github.com/roshancodespace/shonenx/releases
  languages:
    - english
  admin: false
