# Generated code do not commit.
file(TO_CMAKE_PATH "/home/roshan/fvm/versions/3.35.7" FLUTTER_ROOT)
file(TO_CMAKE_PATH "/home/roshan/dev/shonenx" PROJECT_DIR)

set(FLUTTER_VERSION "2.0.7+2" PARENT_SCOPE)
set(FLUTTER_VERSION_MAJOR 2 PARENT_SCOPE)
set(FLUTTER_VERSION_MINOR 0 PARENT_SCOPE)
set(FLUTTER_VERSION_PATCH 7 PARENT_SCOPE)
set(FLUTTER_VERSION_BUILD 2 PARENT_SCOPE)

# Environment variables to pass to tool_backend.sh
list(APPEND FLUTTER_TOOL_ENVIRONMENT
  "FLUTTER_ROOT=/home/roshan/fvm/versions/3.35.7"
  "PROJECT_DIR=/home/roshan/dev/shonenx"
  "DART_DEFINES=QU5JTElTVF9DTElFTlRfSUQ9MjI0ODl8MzY2NDU=,QU5JTElTVF9DTElFTlRfU0VDUkVUPTJJS0YwcXhFRmxrWXdwTW85NlVweUZKbWFMZ3dCSlplNGtaY3pPRzZ8MlVJVmY5YWh1WGxGQlR3S0t6cTZVbWJRcEY2RmdTcm1LMkNVN2o5ZA==,TUFMX0NMSUVOVF9JRD1iNTExY2Y1ZmFiOGI3YTkzOWNjMTBjZjNlOWFkOGQ5NnxlMjFiOWVjMjBkNjk4ZDQ4NGQ3NzVkMzNmMDEwNzVhYQ==,TUFMX0NMSUVOVF9TRUNSRVQ9MjZlZmJlYjA2ZTZhODIyN2Q5MmJmMTg0OTY5ODUyOGRjNmU2M2NkYjg5NmRkODRhN2QxNWEwYWY5Y2ZmZDA5OHwxNTcxZTljY2U0Yzc5MDc3Mjk0MTgwZDgwNDdiNGQzMzY5ZTdiNDE1M2FkOTJmN2YxZmVjYTk5NzMyMmU3NWU1,Q09NTUVOVFVNX0FQSV9VUkw9aHR0cHM6Ly9qbW1saGd2cGt6Z21wd3hhYWZ4aC5zdXBhYmFzZS5jby9mdW5jdGlvbnMvdjE=,UkVMRUFTRV9SRVBPPUNoaXRyYW5zaDE5My9TaG9uZW5Y,RkxVVFRFUl9WRVJTSU9OPTMuMzUuNw==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049YWRjOTAxMDYyNQ==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049MDM1MzE2NTY1YQ==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My45LjI="
  "DART_OBFUSCATION=false"
  "TRACK_WIDGET_CREATION=true"
  "TREE_SHAKE_ICONS=false"
  "PACKAGE_CONFIG=/home/roshan/dev/shonenx/.dart_tool/package_config.json"
  "FLUTTER_TARGET=/home/roshan/dev/shonenx/lib/main.dart"
)
