// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:shonenx/core_new/models/track_search.dart';
import 'package:shonenx/data/hive/models/anime_watch_progress_model.dart';
import 'package:shonenx/features/downloads/model/download_item.dart';
import 'package:shonenx/features/downloads/model/download_status.dart';
import 'package:shonenx/features/home/model/home_page.dart';
import 'package:shonenx/features/settings/model/content_settings_model.dart';
import 'package:shonenx/features/settings/model/download_settings_model.dart';
import 'package:shonenx/features/settings/model/experimental_model.dart';
import 'package:shonenx/features/settings/model/player_model.dart';
import 'package:shonenx/features/settings/model/subtitle_appearance_model.dart';
import 'package:shonenx/features/settings/model/theme_model.dart';
import 'package:shonenx/features/settings/model/ui_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeWatchProgressEntryAdapter());
    registerAdapter(ContentSettingsModelAdapter());
    registerAdapter(DownloadItemAdapter());
    registerAdapter(DownloadSettingsModelAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(EpisodeProgressAdapter());
    registerAdapter(ExperimentalFeaturesModelAdapter());
    registerAdapter(HomePageModelAdapter());
    registerAdapter(PlayerModelAdapter());
    registerAdapter(SubtitleAppearanceModelAdapter());
    registerAdapter(ThemeModelAdapter());
    registerAdapter(TrackSearchAdapter());
    registerAdapter(UiModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeWatchProgressEntryAdapter());
    registerAdapter(ContentSettingsModelAdapter());
    registerAdapter(DownloadItemAdapter());
    registerAdapter(DownloadSettingsModelAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(EpisodeProgressAdapter());
    registerAdapter(ExperimentalFeaturesModelAdapter());
    registerAdapter(HomePageModelAdapter());
    registerAdapter(PlayerModelAdapter());
    registerAdapter(SubtitleAppearanceModelAdapter());
    registerAdapter(ThemeModelAdapter());
    registerAdapter(TrackSearchAdapter());
    registerAdapter(UiModelAdapter());
  }
}
