import 'dart:io';
import 'package:path/path.dart' as p;

/// ---------------------------------------------------------------------------
/// ShonenX Inno Setup Automation Script
/// ---------------------------------------------------------------------------
/// This script parses 'pubspec.yaml' to dynamically generate an Inno Setup 
/// script (.iss) and compiles it into a production-ready Windows Installer.
/// ---------------------------------------------------------------------------

/// Extracts a value from a specific root-level YAML block.
String? extractBlockValue(String content, String block, String key) {
  final blockRegex = RegExp(
    r'^' + RegExp.escape(block) + r':\s*\n((?:\s+.+\n?)*)',
    multiLine: true,
  );

  final blockMatch = blockRegex.firstMatch(content);
  if (blockMatch == null) return null;

  final blockContent = blockMatch.group(1)!;
  final keyRegex = RegExp(
    r'^\s+' + RegExp.escape(key) + r'\s*:\s*(.+)$',
    multiLine: true,
  );

  final keyMatch = keyRegex.firstMatch(blockContent);
  return keyMatch?.group(1)?.trim().replaceAll('"', '').replaceAll("'", '');
}

/// Extracts a standard root-level YAML value.
String? matchValue(String content, String key) {
  final regex = RegExp(r'^' + RegExp.escape(key) + r'\s*:\s*(.+)$', multiLine: true);
  final match = regex.firstMatch(content);
  return match?.group(1)?.trim().replaceAll('"', '').replaceAll("'", '');
}

bool extractBool(String? value) => value != null && value.toLowerCase() == 'true';

void main() {
  // Use 'p.current' to ensure we are anchored to the project root
  final projectRoot = p.current;
  final pubspecFile = File(p.join(projectRoot, 'pubspec.yaml'));

  if (!pubspecFile.existsSync()) {
    stderr.writeln('❌ Error: pubspec.yaml not found in $projectRoot');
    exit(1);
  }

  final content = pubspecFile.readAsStringSync();

  // --- 1. Basic App Metadata ---
  final rawName = matchValue(content, 'name');
  final versionRaw = matchValue(content, 'version');

  if (rawName == null || versionRaw == null) {
    stderr.writeln('❌ Error: Name or Version missing in pubspec.yaml');
    exit(1);
  }

  // Clean version for Windows (1.7.5+11 -> 1.7.5)
  final version = versionRaw.split('+').first;

  // --- 2. Inno Bundle Configurations ---
  final appName = extractBlockValue(content, 'inno_bundle', 'name') ?? rawName;
  final publisher = extractBlockValue(content, 'inno_bundle', 'publisher') ?? 'Darkx-dev';
  final url = extractBlockValue(content, 'inno_bundle', 'url') ?? '';
  final supportUrl = extractBlockValue(content, 'inno_bundle', 'support_url') ?? '';
  final updatesUrl = extractBlockValue(content, 'inno_bundle', 'updates_url') ?? '';
  final appId = extractBlockValue(content, 'inno_bundle', 'id');
  final admin = extractBool(extractBlockValue(content, 'inno_bundle', 'admin'));

  if (appId == null) {
    stderr.writeln('❌ Error: inno_bundle.id is missing! Required for Windows identification.');
    exit(1);
  }

  // --- 3. Resource and Directory Resolution ---
  // We use the .ico generated by 'flutter_launcher_icons' specifically for Windows
  final iconPath = p.join(projectRoot, 'windows', 'runner', 'resources', 'app_icon.ico');
  final hasIcon = File(iconPath).existsSync();

  final buildDir = p.join(projectRoot, 'build', 'windows', 'x64', 'runner', 'Release');
  final outputDir = p.join(projectRoot, 'dist');
  final exeName = '$rawName.exe';

  if (!Directory(buildDir).existsSync()) {
    stderr.writeln('❌ Error: Build artifacts not found at: $buildDir');
    stderr.writeln('👉 Run "flutter build windows --release" first.');
    exit(1);
  }

  // --- 4. ISS Template Construction ---
  final issContent = '''
[Setup]
AppId={{$appId}}
AppName=$appName
AppVersion=$version
AppPublisher=$publisher
AppPublisherURL=$url
AppSupportURL=$supportUrl
AppUpdatesURL=$updatesUrl
DefaultDirName={autopf}\\$appName
DefaultGroupName=$appName
OutputBaseFilename=$appName-Windows-Installer
OutputDir=$outputDir
Compression=lzma
SolidCompression=yes
ArchitecturesInstallIn64BitMode=x64
PrivilegesRequired=${admin ? 'admin' : 'lowest'}
${hasIcon ? 'SetupIconFile=$iconPath' : '; No valid .ico found'}

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "$buildDir\\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\\$appName"; Filename: "{app}\\$exeName"
Name: "{autodesktop}\\$appName"; Filename: "{app}\\$exeName"; Tasks: desktopicon

[Run]
Filename: "{app}\\$exeName"; Description: "{cm:LaunchProgram,$appName}"; Flags: nowait postinstall skipifsilent
''';

  // --- 5. File Writing & Compilation ---
  final issPath = p.join(projectRoot, 'build', 'inno.iss');
  File(issPath)
    ..createSync(recursive: true)
    ..writeAsStringSync(issContent);

  print('✔ Generated Inno Setup script at: $issPath');

  // Targeting the standard installation path of Inno Setup 6
  const isccPath = r'C:\Program Files (x86)\Inno Setup 6\ISCC.exe';
  if (!File(isccPath).existsSync()) {
    stderr.writeln('❌ Error: Inno Setup Compiler (ISCC.exe) not found at $isccPath');
    exit(1);
  }

  print('🚀 Compiling... please wait.');
  final result = Process.runSync(isccPath, [issPath]);

  if (result.exitCode != 0) {
    stderr.writeln('❌ Compilation Failed!');
    stderr.writeln(result.stdout);
    stderr.writeln(result.stderr);
    exit(result.exitCode);
  }

  print('✔ Success! Your installer is ready in: $outputDir');
}