// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:shonenx/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeCardModeAdapter());
    registerAdapter(AnimeWatchProgressEntryAdapter());
    registerAdapter(ContentSettingsModelAdapter());
    registerAdapter(DownloadItemAdapter());
    registerAdapter(DownloadSettingsModelAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(EpisodeProgressAdapter());
    registerAdapter(ExperimentalFeaturesModelAdapter());
    registerAdapter(HomePageModelAdapter());
    registerAdapter(PlayerModelAdapter());
    registerAdapter(SpotlightCardModeAdapter());
    registerAdapter(SubtitleAppearanceModelAdapter());
    registerAdapter(ThemeModelAdapter());
    registerAdapter(UiSettingsAdapter());
    registerAdapter(UniversalNewsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnimeCardModeAdapter());
    registerAdapter(AnimeWatchProgressEntryAdapter());
    registerAdapter(ContentSettingsModelAdapter());
    registerAdapter(DownloadItemAdapter());
    registerAdapter(DownloadSettingsModelAdapter());
    registerAdapter(DownloadStatusAdapter());
    registerAdapter(EpisodeProgressAdapter());
    registerAdapter(ExperimentalFeaturesModelAdapter());
    registerAdapter(HomePageModelAdapter());
    registerAdapter(PlayerModelAdapter());
    registerAdapter(SpotlightCardModeAdapter());
    registerAdapter(SubtitleAppearanceModelAdapter());
    registerAdapter(ThemeModelAdapter());
    registerAdapter(UiSettingsAdapter());
    registerAdapter(UniversalNewsAdapter());
  }
}
